[package]
name = "ferric_compiler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ferric_compiler"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }